#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.config/polybar/launch.sh --hack

xrandr --output HDMI-0 --mode 1920x1080 --refresh 144
nitrogen --restore &
picom &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         1
bspc config window_gap          15
bspc config top_padding         30

bspc config focused_border_color     "#4334eb"

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
